stages:
  - build
  - test
  - deploy
react_build:
  image: node:12.16.0
  stage: build
  before_script:
    - yarn install
  script:
    - yarn build
unit_tests:
  image: node:12.16.0
  stage: test
  before_script:
    - yarn install
  script:
    - yarn test
deploy_app:
  image: node:12.16.0
  stage: deploy
  before_script:
    - yarn install
    - git config --global user.email "alencarvi@gmail.com"
    - git config --global user.name "viniscr"
  script:
    - yarn deploy

