stages:
  - build
  - test
  - deploy
react_build:
  image: node:12.16.0
  stage: build
  before_script:
    - npm install
  script:
    - npm run-script build
unit_tests:
  image: node:12.16.0
  stage: test
  before_script:
    - npm install
  script:
    - npm test
deploy_app:
  image: node:12.16.0
  stage: deploy
  before_script:
    - npm install
  script:
    - npm run deploy

