image: node:12.16.0
variables:
  PUBLIC_URL: /graph-countries-challenge
cache:
  paths:
    - node_modules/

before_script:
  - yarn install

stages:
  - build
  - test
  - deploy
react_build:
  stage: build
  script:
    - yarn build

unit_tests:
  image: node:12.16.0
  stage: test
  before_script:
    - yarn install
  script:
    - yarn test

deploy_app:
  stage: deploy
  script:
    - CI=true yarn build
    - rm -rf public
    - mv public _public # CRA and gitlab pages both use the public folder. Only do this in a build pipeline.
    - mv build public
  artifacts:
    paths:
      - public # GitLab pages serve from a 'public' directory
  only:
    - master # run on master branch

